CREATE DATABASE bjx_crawler;
USE bjx_crawler;
CREATE TABLE pages(id BIGINT(7) NOT NULL AUTO_INCREMENT, url VARCHAR(63) NOT NULL, title VARCHAR(255), source VARCHAR(255), author VARCHAR(127), edit_date DATE, edit_time TIME, content VARCHAR(21000), scrapted TIMESTAMP DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY(id));